<a href="https://colab.research.google.com/github/jpinzonc/TensorFlow2/blob/master/Colab_2_TensorFlow_2_0_Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## TensorFlow 1.X




### Installing TensorFlow 1.X



In [1]:
!pip install tensorflow-gpu==1.13.1

     |████████████████████████████████| 345.2MB 55kB/s 
     |████████████████████████████████| 3.2MB 38.9MB/s 
     |████████████████████████████████| 368kB 43.8MB/s 
ERROR: tensorflow 1.14.0 has requirement tensorboard<1.15.0,>=1.14.0, but you'll have tensorboard 1.13.1 which is incompatible.
ERROR: tensorflow 1.14.0 has requirement tensorflow-estimator<1.15.0rc0,>=1.14.0rc0, but you'll have tensorflow-estimator 1.13.0 which is incompatible.
  Found existing installation: tensorboard 1.14.0
    Uninstalling tensorboard-1.14.0:
      Successfully uninstalled tensorboard-1.14.0
  Found existing installation: tensorflow-estimator 1.14.0
    Uninstalling tensorflow-estimator-1.14.0:
      Successfully uninstalled tensorflow-estimator-1.14.0


In [0]:
import tensorflow as tf

In [3]:
tf.__version__

'1.13.1'

### Constants

#### Defining a constant

In [0]:
# Defining a TensorFlow constant
tensor = tf.constant([[23, 4], [32, 51]])

In [6]:
tensor

<tf.Tensor 'Const_1:0' shape=(2, 2) dtype=int32>

In [7]:
# If a session is not initialized, we cannot access the values of the constant
tensor.eval()

ValueError: ignored

#### Getting the values of a constant

In [0]:
session = tf.Session()

In [0]:
session.run(tf.global_variables_initializer())

In [0]:
tensor_value = session.run(tensor)

In [11]:
tensor_value

array([[23,  4],
       [32, 51]], dtype=int32)

### Variables

#### Defining a variable

In [12]:
# Defining a TensorFlow variable
variable = tf.Variable([[30, 20], [10, 45]])

Instructions for updating:
Colocations handled automatically by placer.


In [13]:
variable

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32_ref>

In [14]:
# If a session is not initialized, we cannot access the values of the variable
variable.eval()

ValueError: ignored

#### Getting the values of a variable

In [0]:
# Initializing a session
session = tf.Session()

In [0]:
# Initializing ALL the variables from the session
session.run(tf.global_variables_initializer())

In [16]:
# Running the eval method on the environment with the initialized session to retrieve values from it
variable.eval(session)

array([[30, 20],
       [10, 45]], dtype=int32)

## TensorFlow 2.0

### Installing TensorFlow 2.0

In [1]:
!pip install tensorflow-gpu==2.0.0-alpha0

In [0]:
import tensorflow as tf
import numpy as np

In [3]:
tf.__version__

'2.0.0-alpha0'

### Constants

#### Defining a constant

In [0]:
# Defining a constant in TensorFlow 2.0
tensor_20 = tf.constant([[23, 4], [32, 51]])

In [5]:
tensor_20

<tf.Tensor: id=0, shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [6]:
# Getting the shape of a tensor
tensor_20.shape

TensorShape([2, 2])

#### Getting the values of a constant

In [7]:
# Getting the values straight from a TensorFlow constant with numpy, and without the need of a session
tensor_20.numpy()

array([[23,  4],
       [32, 51]], dtype=int32)

In [0]:
# We are able to convert a numpy array back to a TensorFlow tensor as well
numpy_tensor = np.array([[23,  4], [32, 51]])

In [0]:
tensor_from_numpy = tf.constant(numpy_tensor)

In [10]:
tensor_from_numpy

<tf.Tensor: id=3, shape=(2, 2), dtype=int64, numpy=
array([[23,  4],
       [32, 51]])>

### Variables

#### Defining a variable

In [11]:
tf2_variable = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

#### Getting the values of a variable

In [12]:
tf2_variable.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

#### Changing a specific value in the variable

In [13]:
tf2_variable[0, 2].assign(100)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

In [14]:
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

### Operations with tensors

In [15]:
tensor = tf.constant([[1, 2], [3, 4]])
tensor

<tf.Tensor: id=27, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

#### Addition between a scalar and a tensor

In [16]:
tensor + 2

<tf.Tensor: id=30, shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>

#### Multiplication between a scalar and a tensor

In [17]:
tensor * 5

<tf.Tensor: id=33, shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [15, 20]], dtype=int32)>

#### Using Numpy functions on TensorFlow tensors

In [18]:
# Getting the squares of all numbers in a TensorFlow tensor object
np.square(tensor)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [19]:
# Getting the square root of all numbers in a tensorflow tensor object
np.sqrt(tensor)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

#### Dot product between two tensors

In [20]:
 np.dot(tensor, tensor_20)

array([[ 87, 106],
       [197, 216]], dtype=int32)

### Strings in TensorFlow 2.0

In [21]:
tf_string = tf.constant("TensorFlow")
tf_string

<tf.Tensor: id=41, shape=(), dtype=string, numpy=b'TensorFlow'>

#### Simple string operations

In [22]:
tf.strings.length(tf_string)

<tf.Tensor: id=43, shape=(), dtype=int32, numpy=10>

In [23]:
tf.strings.unicode_decode(tf_string, "UTF8")

<tf.Tensor: id=48, shape=(10,), dtype=int32, numpy=array([ 84, 101, 110, 115, 111, 114,  70, 108, 111, 119], dtype=int32)>

#### Storing arrays of strings

In [0]:
tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "AI"])

In [25]:
# Iterating through the TF string array
for string in tf_string_array:
  print(string)

tf.Tensor(b'TensorFlow', shape=(), dtype=string)
tf.Tensor(b'Deep Learning', shape=(), dtype=string)
tf.Tensor(b'AI', shape=(), dtype=string)


In [29]:
tf_string_array[0].numpy()

b'TensorFlow'

In [31]:
tf_string_array.numpy()

array([b'TensorFlow', b'Deep Learning', b'AI'], dtype=object)